# Generated by Django 4.2.6 on 2024-01-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_task_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
