# Generated by Django 4.2.6 on 2024-01-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicChatRoom',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessage',
        ),
    ]
