# Generated by Django 4.2.6 on 2023-11-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
