# Generated by Django 4.2.6 on 2023-10-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_activity_delete_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
