# Generated by Django 4.2.6 on 2023-11-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_activity_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=50)),
                ('arrival_airport', models.CharField(max_length=50)),
            ],
        ),
    ]
